service: express-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128

vpc:
  securityGroupIds:
    - sg-1923466d
  subnetIds:
    - subnet-dba66193
    - subnet-48e6312e

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /api/v1/setting
          method: get
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/setting
          method: post
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/setting/{id}
          method: patch
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/log
          method: get
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/portfolio
          method: get
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/portfolio/{id}
          method: get
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/portfolio
          method: post
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/portfolio/{id}
          method: patch
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/user
          method: get
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/user/logout
          method: delete
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/user
          method: post
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/user/login
          method: post
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /api/v1/user/token
          method: post
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'

plugins:
  - serverless-offline
