service: express-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128

vpc:
  securityGroupIds:
    - sg-1923466d
  subnetIds:
    - subnet-dba66193

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
