service: express-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128

vpc:
  securityGroupIds:
    - sg-1923466d
  subnetIds:
    - subnet-dba66193
    - subnet-48e6312e

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            - enabled: true
            - headers: 'Content-Type,Authorization,x-auth'

plugins:
  - serverless-offline
