// System setting
export const FETCHING_SYSTEM_SETTING = 'FETCHING_SYSTEM_SETTING';
export const FETCH_SYSTEM_SETTING_SUCCESS = 'FETCH_SYSTEM_SETTING_SUCCESS';
export const FETCH_SYSTEM_SETTING_FAILURE = 'FETCH_SYSTEM_SETTING_FAILURE';

// Portfolio
export const FETCHING_PORTFOLIO_LIST = 'FETCHING_PORTFOLIO_LIST';
export const FETCH_PORTFOLIO_LIST_SUCCESS = 'FETCH_PORTFOLIO_LIST_SUCCESS';
export const FETCH_PORTFOLIO_LIST_FAILURE = 'FETCH_PORTFOLIO_LIST_FAILURE';