// System setting
export const FETCHING_SYSTEM_SETTING = 'FETCHING_SYSTEM_SETTING';
export const FETCH_SYSTEM_SETTING_SUCCESS = 'FETCH_SYSTEM_SETTING_SUCCESS';
export const FETCH_SYSTEM_SETTING_FAILURE = 'FETCH_SYSTEM_SETTING_FAILURE';
export const UPDATING_SYSTEM_SETTING = 'UPDATING_SYSTEM_SETTING';
export const UPDATE_SYSTEM_SETTING_SUCCESS = 'UPDATE_SYSTEM_SETTING_SUCCESS';
export const UPDATE_SYSTEM_SETTING_FAILURE = 'UPDATE_SYSTEM_SETTING_FAILURE';

// Portfolio
export const FETCHING_PORTFOLIO_LIST = 'FETCHING_PORTFOLIO_LIST';
export const FETCH_PORTFOLIO_LIST_SUCCESS = 'FETCH_PORTFOLIO_LIST_SUCCESS';
export const FETCH_PORTFOLIO_LIST_FAILURE = 'FETCH_PORTFOLIO_LIST_FAILURE';
export const FETCHING_SPECIFIC_PORTFOLIO = 'FETCHING_SPECIFIC_PORTFOLIO';
export const FETCH_SPECIFIC_PORTFOLIO_SUCCESS = 'FETCH_SPECIFIC_PORTFOLIO_SUCCESS';
export const FETCH_SPECIFIC_PORTFOLIO_FAILURE = 'FETCH_SPECIFIC_PORTFOLIO_FAILURE';
export const UPDATING_PORTFOLIO = 'UPDATING_PORTFOLIO';
export const UPDATE_PORTFOLIO_SUCCESS = 'UPDATE_PORTFOLIO_SUCCESS';
export const UPDATE_PORTFOLIO_FAILURE = 'UPDATE_PORTFOLIO_FAILURE';

// User
export const START_LOGIN_PROCESS = 'START_LOGIN_PROCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const START_LOGOUT_PROCESS = 'START_LOGOUT_PROCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CHECKING_TOKEN = 'CHECKING_TOKEN';
export const TOKEN_VALID_SUCCESS = 'TOKEN_VALID_SUCCESS';
export const TOKEN_VALID_FAILURE = 'TOKEN_VALID_FAILURE';
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE';

// Log
export const FETCHING_SERVER_LOG = 'FETCHING_SERVER_LOG';
export const FETCH_SERVER_LOG_SUCCESS = 'FETCH_SERVER_LOG_SUCCESS';
export const FETCH_SERVER_LOG_FAILURE = 'FETCH_SERVER_LOG_FAILURE';